spring.application.name=warehouse-orm
spring.datasource.url=jdbc:mysql://localhost:3306/example
spring.datasource.username=springuser
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect